const Terns = () => {
  return (
    <div className="hero bg-customGreenPrimary p-30 w-full ">
      <div className="hero-content text-left">
        <div className="max-w-full">
          <h2 className="text-4xl text-customYellowHeading mb-10">
            Terms & Conditions:
          </h2>
          <ul className="list-disc pl-5">
            <li>
              Affiliates are prohibited from adding their own member ID to their
              downline.
            </li>
            <li>
              The percentage of Affiliate Revenue Share is based on the revenue
              generated by downline members. To qualify for a higher percentage,
              affiliates must meet all specified criteria.
            </li>
            <li>
              Each member in the downline is allowed only one unique account.
              Multiple accounts created by the same member will not be included
              in the revenue share calculations.
            </li>
            <li>
              9wickets from Sports platform and P2P games are excluded from the
              affiliate calculation.
            </li>
            <li>
              Any negative balance for a given month will be carried over to the
              next month.
            </li>
            <li>
              The Affiliate Revenue share percentage is determined by the
              member’s net monthly loss after deducting promotions/bonuses,
              cashback/refunds, negative carryover, and a 20% platform fee.
            </li>
            <li>
              Earned revenue shares will be transferred between the 1st and 5th
              working days of each month. Affiliates can request withdrawals
              from their designated affiliate account.
            </li>
            <li>
              Affiliates acknowledge that gambling is a regulated industry and
              agree to provide any required information or assistance to ensure
              regulatory compliance.
            </li>
            <li>
              Affiliates understand the inherent risks of gaming, including the
              potential loss of money.
            </li>
            <li>
              Affiliates agree to adhere to the methods, rules, and procedures
              associated with the gaming service requested.
            </li>
            <li>
              This application form is completed and submitted by the Affiliate
              personally.
            </li>
            <li>
              Affiliates guarantee that all information provided in the form is
              true, accurate, and valid.
            </li>
            <li>
              HEYBAJI is not liable for any risk associated with losing User
              ID/Password or sharing this information with others. If you
              suspect your User ID has been compromised, please contact HEYBAJI
              support immediately.
            </li>
            <li>
              Affiliates acknowledge and confirm that they have read,
              understood, and agreed to all the terms and conditions stated.
            </li>
            <li>
              HEYBAJI uses user-provided information solely for specific
              purposes, such as sending electronic newsletters and providing
              requested information, including promotions and member services.
              HEYBAJI does not use individual user information for other
              purposes and will not disclose it to third parties without
              consent.
            </li>
            <li>HEYBAJI’s Terms and Conditions apply.</li>
            <li>
              Affiliates must have at least 5 active players to qualify for
              commissions.
            </li>
            <li>
              We do not approve of SEO traffic derived from our own brand name.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default Terns;
